#
## GPT4All Chatbot conditionning file
## Author : @ParisNeo
## Version : 1.1
## Description :
## An NLP needs conditionning to instruct it to be whatever we want it to be.
## This file is used by the pyaipersonality module to condition the personality of the model you are
## talking to.
#
#
ai_message_prefix: '# langchain_pdf:

  '
author: ParisNeo
category: internet
dependencies: ['langchain','PyPDF2','python-dotenv']
disclaimer: ''
language: en_XX
link_text: '

  '
name: Langchain_pdf
personality_conditioning: '###Instruction: 
  Chat about a pdf you give the AI
  '
personality_description: 'This personality uses the langchain library to parse a big pdf file and talk about it'
user_message_prefix: '### Human:
  formulate a search query for this question:
  '
user_name: user
version: 1.0.0
welcome_message: ''
anti_prompts: ["### Human", "### gpt4Internet", "### Assistant", "### Search engine:"]

# Here are default model parameters
model_temperature: 0.1 # higher: more creative, lower more deterministic
model_n_predicts: 1024 # higher: generates many words, lower generates
model_top_k: 5
model_top_p: 0.98
model_repeat_penalty: 1.0
model_repeat_last_n: 60

# Here are special configurations for the processor 
processor_cfg:
  custom_workflow: true
  process_model_input: false
  process_model_output: false
  pdf_file_path:  path/to/your/pff.pdf # Path to the PDF that will be discussed